### ISSUE TITLE
Mejorar pantalla de captura de produccion de huevo

### ISSUE THREAD

**Issue by makeplerc** [makeplerc/avi_planner_r#33]
El usuario final menciona que es muy tardado hacer la captura de esta manera. 
![Screenshot](https://user-images.githubusercontent.com/46659319/56851876-b972a100-68d9-11e9-8271-55a809153a13.png)

**Comment by izzihector** [comment]
Se me ocurre hacer el proceso de dos maneras uno es hacer mediante un excel de importación eso evita los tiempos de carga de odoo y dos hacer un  wizar que pida los datos y los agregue a la tabla

**Comment by makeplerc** [comment]
@izzihector de hecho acabo de hacer un wizard y se lo presente a los usuarios, quedaron felices con el cambio, hoy reanudad la captura.

**Comment by makeplerc** [comment]
![Screenshot (2)](https://user-images.githubusercontent.com/46659319/56907785-a0e5c080-6a6a-11e9-9101-55532c9793c1.png)
